[package]
name = "cas-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
csv = "1"
proc-macro2 = "1"
quote = "1"

[dependencies]
nalgebra = { version = "0.30", default-features = false, features = ["macros"] }
uom = { version = "0", default-features = false, features = ["f32", "u8", "si"] }
