[package]
name = "advisory_viewer"
version = "0.1.0"
authors = ["Wanja Zaeske <wanja.zaeske@dlr.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = "0.17.0" # Gives us egui, epi and web+native backends
opencas = { path = "../opencas" }
uom = "*"
rayon = "1.5" #Gives easy to use parallelized iterators
arc-swap = "1.5" #For atomic double buffers
#kd-tree = "0.4" #KD Tree implementation for dynamic image calculation
atomic-counter = "1.0" #Track progress of image generator
ordered-float = "2.10"
strum = { version = "0", features = [ "derive" ] }

serde = { version = "1", features = ["derive"], optional = true }

[features]
default = []
persistence = ["eframe/persistence", "serde"] # Enable if you want to persist app state on shutdown
