[package]
name = "advisory_viewer"
version = "0.1.0"
authors = ["Wanja Zaeske <wanja.zaeske@dlr.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
egui = { features = [ "multi_threaded" ], git = "https://github.com/wucke13/egui", branch = "dev/wucke13" }
eframe = { features = [ "persistence" ], git = "https://github.com/wucke13/egui", branch = "dev/wucke13" }
opencas = { path = "../opencas" }
uuid = { version = "0.8", features = [ "v4" ] }
uom = "*"
arc-swap = "1.5" #For atomic double buffers
#kd-tree = "0.4" #KD Tree implementation for dynamic image calculation
atomic-counter = "1.0" #Track progress of image generator
ordered-float = "2.10"
strum = { version = "0", features = [ "derive" ] }

serde = { version = "1", features = ["derive"] }
