/// This module contains autogenerated instances of all nnet files found in the `nnets` directory.
#[allow(dead_code)]
#[allow(non_upper_case_globals)]
mod nnets {
    use crate::inference::{Layer, NNet};
    use nalgebra::{matrix, vector};

    include!(concat!(env!("OUT_DIR"), "/nnets.rs"));
}

mod inference;
