name: "Deploy Github Page"
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: aeronautical-informatics
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ github.job }}-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build Website
        run: |
          cd advisory_viewer
          nix develop --command trunk build --public-url https://${{ github.repository_owner }}.github.io/openCAS --release
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./advisory_viewer/dist
